name: 部署

on:
  push:
    branches:
      - main  # 仅在推送到 main 分支时触发

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 检出代码
      uses: actions/checkout@v4  # 使用最新的 v4 版本

    - name: 设置 Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.16.0'  # 使用 Node.js v18.16.0 版本

    - name: 安装依赖
      run: npm install

    - name: 构建项目
      run: npm run build:prod  # 使用生产模式进行构建

    - name: 配置 SSH
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: 部署到服务器
      env:
        SERVER_HOST: ${{ secrets.SERVER_HOST }}
        DEPLOY_PATH: ${{ secrets.BLOG_DEPLOY_PATH }}
      run: |
        rsync -avz -e "ssh -o StrictHostKeyChecking=no" dist/ root@$SERVER_HOST:$BLOG_DEPLOY_PATH
